// tailwind.config.js
//
// This is a SOURCE file. It is NOT generated.
// Edit and maintain this file directly in version control.
//
// All token mappings reference CSS custom properties (variables) generated by Style Dictionary.
// Do NOT edit build/css/variables.css directly—run the token build process to update variables.
//
// Make sure to import 'build/css/variables.css' in your main CSS entry (e.g. index.css or App.css).

module.exports = {
  theme: {
    colors: {
      primary: 'var(--colorBlue500)',
      secondary: 'var(--colorPurple500)',
      error: 'var(--colorRed500)',
      warning: 'var(--colorOrange500)',
      info: 'var(--colorCyan500)',
      success: 'var(--colorGreen500)',
      gray: {
        50: 'var(--colorGrey50)',
        100: 'var(--colorGrey100)',
        200: 'var(--colorGrey200)',
        300: 'var(--colorGrey300)',
        400: 'var(--colorGrey400)',
        500: 'var(--colorGrey500)',
        600: 'var(--colorGrey600)',
        700: 'var(--colorGrey700)',
        800: 'var(--colorGrey800)',
        900: 'var(--colorGrey900)',
      },
    },
    borderRadius: {
      sm: 'var(--borderRadiusSm)',
      md: 'var(--borderRadiusMd)',
      lg: 'var(--borderRadiusLg)',
      xl: 'var(--borderRadiusXl)',
      none: 'var(--borderRadiusNone)',
    },
    fontFamily: {
      poppins: 'var(--fontFamiliesPoppins), sans-serif',
      inter: 'var(--fontFamiliesInter), sans-serif',
      roboto: 'var(--fontFamiliesRoboto), sans-serif',
      mono: 'var(--fontFamiliesRobotoMono), monospace',
    },
    fontSize: {
      xs: 'var(--fontSizes10)',
      sm: 'var(--fontSizes12)',
      base: 'var(--fontSizes14)',
      lg: 'var(--fontSizes16)',
      xl: 'var(--fontSizes18)',
      '2xl': 'var(--fontSizes21)',
      '3xl': 'var(--fontSizes24)',
      '4xl': 'var(--fontSizes32)',
      '5xl': 'var(--fontSizes40)',
      '6xl': 'var(--fontSizes48)',
    },
    spacing: {
      0: 'var(--spacings0)',
      1: 'var(--spacings1)',
      2: 'var(--spacings2)',
      3: 'var(--spacings3)',
      4: 'var(--spacings4)',
      5: 'var(--spacings5)',
      6: 'var(--spacings6)',
      7: 'var(--spacings7)',
      8: 'var(--spacings8)',
      9: 'var(--spacings9)',
      10: 'var(--spacings10)',
      11: 'var(--spacings11)',
      12: 'var(--spacings12)',
    },
    // Add other theme keys as needed
  },
  // ...rest of your Tailwind config (content, plugins, etc.)
}; 