import * as tokens from '../../build/tokens.mjs';

export const typography = {
  fontFamily: `${tokens.fontFamiliesRoboto}, ${tokens.fontFamiliesInter}, ${tokens.fontFamiliesPoppins}, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif`,
  fontSize: 14, // MUI expects px as a number
  fontWeightLight: 300,
  fontWeightRegular: Number(tokens.fontWeightsRegular),
  fontWeightMedium: Number(tokens.fontWeightsSemibold), // Use semibold if no medium
  fontWeightBold: Number(tokens.fontWeightsBold),
  htmlFontSize: 16,
  h1: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 48,
    fontWeight: Number(tokens.fontWeightsBold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  h2: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 40,
    fontWeight: Number(tokens.fontWeightsBold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  h3: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 32,
    fontWeight: Number(tokens.fontWeightsBold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  h4: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 24,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  h5: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 21,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  h6: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 18,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  subtitle1: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 16,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  subtitle2: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 14,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  body1: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 16,
    fontWeight: Number(tokens.fontWeightsRegular),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  body2: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 14,
    fontWeight: Number(tokens.fontWeightsRegular),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  button: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 14,
    fontWeight: Number(tokens.fontWeightsSemibold),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
    textTransform: 'uppercase',
  },
  caption: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 12,
    fontWeight: Number(tokens.fontWeightsRegular),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
  },
  overline: {
    fontFamily: tokens.fontFamiliesRoboto,
    fontSize: 12,
    fontWeight: Number(tokens.fontWeightsRegular),
    lineHeight: 1.2,
    letterSpacing: tokens.letterSpacingsDefault,
    textTransform: 'uppercase',
  },
};